- hosts: all
  become: True
  tasks: 
  - name: Install httpd
    package:
      name: httpd
      state: present

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes
