apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80



# kubectl create deployment nginx-deployment –image nginx  –port=80
# kubectl set image deployment/nginx-deployment nginx=nginx:1.161
# kubectl describe deployments
# kubectl get rs
# kubectl rollout history deployment/nginx-deployment
# kubectl rollout undo deployment/nginx-deployment
# kubectl rollout undo deployment/nginx-deployment --to-revision=2
## Create hpa: 
# kubectl autoscale deployment/nginx-deployment --min=10 --max=15 --cpu-percent=80



