apiVersion: v1
kind: Service
metadata: 
  name: webserver-service-nodeport
spec:
  type: NodePort      # ClusterIP 
  selector:
    name: webserver

  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
